// src/vue/App.vue
<template>
    <div id="app">
        Data from outer property: {{ title }}
        <br />
        <br />
        <!-- Setting the ref on the account list is the key part for using native event dispatching. -->
        <ul ref="accountList">
            <li
                v-for="account in accounts"
                :key="account.Id"
                v-on:click="handleClick(account.Id)"
            >
                {{ account.Id }} - {{ account.Name }}
            </li>
        </ul>
    </div>
</template>

<script>
import getAccounts from "@salesforce/apex/AccountController.getAccounts";

export default {
    name: "App",
    props: {
        accounts: Array,
        title: String
    },
    methods: {
        handleClick: function (accountId) {
            const evt = new CustomEvent("sendaccount", {
                detail: { accountId },
                bubbles: true,
                composed: true
            });
            // Here we reference the `accountList` ref to dispatch the native event.
            this.$refs.accountList.dispatchEvent(evt);
        }
    },
    mounted: function () {
        getAccounts()
            .then((result) => (this.accounts = result))
            .catch((error) => console.log(error));
    }
};
</script>

<style>
#app {
    font-family: Avenir, Helvetica, Arial, sans-serif;
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
    color: #2c3e50;
    padding: 6px;
}

li {
    cursor: pointer;
}
</style>

// src/svelte/App.svelte
<script>
    import { onMount, createEventDispatcher } from "svelte";
    import getAccounts from "@salesforce/apex/AccountController.getAccounts";

    export let title;
    const dispatch = createEventDispatcher();

    let el; // We need this el variable to store later the ul ref for event dispatching.

    let accounts = [];

    onMount(() => {
        getAccounts()
            .then(result => (accounts = result))
            .catch(error => console.log(error));
    });

    // Events
    function sendAccount(accountId) {
        const evt = new CustomEvent("sendaccount", {
            detail: { accountId },
            bubbles: true,
            composed: true
        });
        el.dispatchEvent(evt);
    }
</script>

<style>
    main {
        padding: 1em;
        max-width: 240px;
        margin: 0 auto;
    }

    li {
        cursor: pointer;
    }

    @media (min-width: 640px) {
        main {
            max-width: none;
        }
    }
</style>

<main>
    <!-- Binding the el is the key part to leverage native event dispatching. -->
    <div class="slds-p-around_medium" bind:this={el}>
        Data from outer property: {title}
        <br />
        <br />
        <ul>
            {#each accounts as account}
                <li on:click={sendAccount(account.Id)}>
                    {account.Id} - {account.Name}
                </li>
            {/each}
        </ul>
    </div>

</main>
